name: Farm Commits per bocaletto-luca

on:
  schedule:
    - cron: '0 */8 * * *'    # ogni 8 ore
  workflow_dispatch:

jobs:
  farm-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configura autore Git
        run: |
          git config user.name "bocaletto-luca"
          git config user.email "${{ secrets.BOCA_EMAIL }}"

      - name: Prepara src/ e timestamp
        run: |
          mkdir -p src
          echo "TIMESTAMP=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Commit src/test.txt
        run: |
          echo "farm at $TIMESTAMP" > src/test.txt
          git add src/test.txt
          git commit -m "chore: update test.txt at $TIMESTAMP"

      - name: Commit src/test2.txt
        run: |
          echo "farm at $TIMESTAMP" > src/test2.txt
          git add src/test2.txt
          git commit -m "chore: update test2.txt at $TIMESTAMP"

      - name: Push su main
        run: git push origin main
